import { useState, useRef, useCallback } from 'react'
import { useNavigate } from 'react-router-dom'
import { Upload, ArrowUp, FileText, X, Loader2 } from 'lucide-react'
import Navbar from '../components/layout/Navbar'
import MascotBird from '../components/three/MascotBird'

// Types
type QuizType = 'multiple-choice' | 'flashcard' | 'matching'
type QuestionCount = 10 | 15 | 25

interface UploadedFile {
  file: File
  name: string
  size: string
}

interface GeneratedQuestion {
  questionText: string
  options: { text: string; isCorrect: boolean }[]
  timeLimit: number
  points: number
}

interface GeneratedQuizData {
  title: string
  type: QuizType
  questions: GeneratedQuestion[]
}

const AIGeneratePage = () => {
  const navigate = useNavigate()
  
  const [selectedQuizType, setSelectedQuizType] = useState<QuizType>('multiple-choice')
  const [selectedCount, setSelectedCount] = useState<QuestionCount>(10)
  const [prompt, setPrompt] = useState('')
  const [uploadedFile, setUploadedFile] = useState<UploadedFile | null>(null)
  const [isGenerating, setIsGenerating] = useState(false)
  const [isDragging, setIsDragging] = useState(false)
  
  const fileInputRef = useRef<HTMLInputElement>(null)

  const quizTypes: { value: QuizType; label: string }[] = [
    { value: 'multiple-choice', label: 'Multiple Choices' },
    { value: 'flashcard', label: 'Flashcards' },
    { value: 'matching', label: 'Matching' },
  ]

  const questionCounts: QuestionCount[] = [10, 15, 25]

  const formatFileSize = (bytes: number): string => {
    if (bytes < 1024) return bytes + ' B'
    if (bytes < 1024 * 1024) return (bytes / 1024).toFixed(1) + ' KB'
    return (bytes / (1024 * 1024)).toFixed(1) + ' MB'
  }

  const handleFileSelect = useCallback((file: File) => {
    if (file.type !== 'application/pdf') {
      alert('Please upload a PDF file')
      return
    }
    if (file.size > 10 * 1024 * 1024) {
      alert('File size must be less than 10MB')
      return
    }
    setUploadedFile({
      file,
      name: file.name,
      size: formatFileSize(file.size),
    })
  }, [])

  const handleFileInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]
    if (file) handleFileSelect(file)
  }

  const handleDragOver = (e: React.DragEvent) => {
    e.preventDefault()
    setIsDragging(true)
  }

  const handleDragLeave = (e: React.DragEvent) => {
    e.preventDefault()
    setIsDragging(false)
  }

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault()
    setIsDragging(false)
    const file = e.dataTransfer.files?.[0]
    if (file) handleFileSelect(file)
  }

  const removeFile = () => {
    setUploadedFile(null)
    if (fileInputRef.current) {
      fileInputRef.current.value = ''
    }
  }

  // Generate sample quiz data (in production, this would call the AI API)
  const generateSampleQuizData = (): GeneratedQuizData => {
    // Sample questions - in production, these would be generated by Gemini AI
    const sampleQuestions: GeneratedQuestion[] = [
      {
        questionText: "Which HTTP status code means the requested resource was found but moved permanently to a new URL?",
        options: [
          { text: "200", isCorrect: false },
          { text: "301", isCorrect: true },
          { text: "404", isCorrect: false },
          { text: "500", isCorrect: false }
        ],
        timeLimit: 30,
        points: 10
      },
      {
        questionText: "Which HTTP status code indicates a successful request?",
        options: [
          { text: "200", isCorrect: true },
          { text: "301", isCorrect: false },
          { text: "404", isCorrect: false },
          { text: "500", isCorrect: false }
        ],
        timeLimit: 30,
        points: 10
      },
      {
        questionText: "Which HTTP status code means 'Not Found'?",
        options: [
          { text: "200", isCorrect: false },
          { text: "301", isCorrect: false },
          { text: "404", isCorrect: true },
          { text: "500", isCorrect: false }
        ],
        timeLimit: 30,
        points: 10
      },
      {
        questionText: "Which HTTP status code indicates an Internal Server Error?",
        options: [
          { text: "200", isCorrect: false },
          { text: "301", isCorrect: false },
          { text: "404", isCorrect: false },
          { text: "500", isCorrect: true }
        ],
        timeLimit: 30,
        points: 10
      },
      {
        questionText: "Which HTTP status code means 'Bad Request'?",
        options: [
          { text: "400", isCorrect: true },
          { text: "401", isCorrect: false },
          { text: "403", isCorrect: false },
          { text: "405", isCorrect: false }
        ],
        timeLimit: 30,
        points: 10
      },
      {
        questionText: "Which HTTP status code indicates 'Unauthorized'?",
        options: [
          { text: "400", isCorrect: false },
          { text: "401", isCorrect: true },
          { text: "403", isCorrect: false },
          { text: "405", isCorrect: false }
        ],
        timeLimit: 30,
        points: 10
      },
      {
        questionText: "Which HTTP status code means 'Forbidden'?",
        options: [
          { text: "400", isCorrect: false },
          { text: "401", isCorrect: false },
          { text: "403", isCorrect: true },
          { text: "405", isCorrect: false }
        ],
        timeLimit: 30,
        points: 10
      },
      {
        questionText: "Which HTTP status code indicates 'Created'?",
        options: [
          { text: "200", isCorrect: false },
          { text: "201", isCorrect: true },
          { text: "202", isCorrect: false },
          { text: "204", isCorrect: false }
        ],
        timeLimit: 30,
        points: 10
      },
      {
        questionText: "Which HTTP status code means 'No Content'?",
        options: [
          { text: "200", isCorrect: false },
          { text: "201", isCorrect: false },
          { text: "202", isCorrect: false },
          { text: "204", isCorrect: true }
        ],
        timeLimit: 30,
        points: 10
      },
      {
        questionText: "Which HTTP status code indicates a temporary redirect?",
        options: [
          { text: "301", isCorrect: false },
          { text: "302", isCorrect: true },
          { text: "304", isCorrect: false },
          { text: "307", isCorrect: false }
        ],
        timeLimit: 30,
        points: 10
      }
    ]

    // Return only the selected number of questions
    return {
      title: uploadedFile ? `Quiz from ${uploadedFile.name}` : 'Generated Quiz',
      type: selectedQuizType,
      questions: sampleQuestions.slice(0, selectedCount)
    }
  }

  const handleGenerate = async () => {
    if (!uploadedFile) {
      alert('Please upload a PDF file first')
      return
    }

    setIsGenerating(true)
    
    try {
      // Simulate API call delay
      await new Promise(resolve => setTimeout(resolve, 2000))
      
      console.log('Generating quiz:', {
        type: selectedQuizType,
        count: selectedCount,
        prompt,
        file: uploadedFile.name,
      })
      
      // Generate quiz data
      const quizData = generateSampleQuizData()
      
      // Navigate based on quiz type
      if (selectedQuizType === 'multiple-choice') {
        navigate('/quiz/multiple-choice', { 
          state: { quizData } 
        })
      } else if (selectedQuizType === 'flashcard') {
        // TODO: Navigate to flashcard page
        navigate('/quiz/flashcard', { 
          state: { quizData } 
        })
      } else if (selectedQuizType === 'matching') {
        // TODO: Navigate to matching page
        navigate('/quiz/matching', { 
          state: { quizData } 
        })
      }
      
    } catch (error) {
      console.error('Error generating quiz:', error)
      alert('Failed to generate quiz. Please try again.')
    } finally {
      setIsGenerating(false)
    }
  }

  const handlePromptSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    handleGenerate()
  }

  return (
    <div className="fixed inset-0 overflow-hidden">
      <Navbar />
      
      {/* Main Content */}
      <main className="h-full pt-20 pb-28 px-8">
        <div className="max-w-7xl mx-auto h-full">
          <div className="flex items-center justify-between gap-8 h-full">
            
            {/* Left Side - 3D Mascot */}
            <div className="flex-1 h-full flex items-center justify-center relative">
              {/* Glow effect */}
              <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
                <div className="w-[400px] h-[400px] rounded-full bg-purple-500/10 blur-[100px]" />
              </div>
              
              {/* 3D Canvas Container */}
              <div className="w-full h-[450px] relative z-10">
                <MascotBird />
              </div>
            </div>

            {/* Right Side - Options Panel */}
            <div className="w-[520px] flex-shrink-0">
              <div className="relative bg-[#1a1a2e]/80 backdrop-blur-xl rounded-3xl border border-purple-500/20 p-10">
                {/* Gradient overlay */}
                <div className="absolute inset-0 rounded-3xl bg-gradient-to-br from-purple-500/10 via-transparent to-blue-500/5 pointer-events-none" />
                
                <div className="relative space-y-10">
                  {/* Quiz Type Selection */}
                  <div>
                    <h3 className="text-white/90 text-lg font-medium mb-5">
                      Choose the question type you want to generate
                    </h3>
                    <div className="flex gap-3">
                      {quizTypes.map((type) => (
                        <button
                          key={type.value}
                          onClick={() => setSelectedQuizType(type.value)}
                          className={`
                            flex-1 py-4 px-4 rounded-xl text-sm font-medium whitespace-nowrap
                            transition-all duration-200
                            ${selectedQuizType === type.value
                              ? 'bg-purple-600 text-white'
                              : 'bg-[#2a2a40]/80 text-white/60 border border-white/10 hover:bg-[#353550] hover:text-white/80'
                            }
                          `}
                        >
                          {type.label}
                        </button>
                      ))}
                    </div>
                  </div>

                  {/* Divider */}
                  <div className="h-px bg-purple-500/30" />

                  {/* Question Count */}
                  <div>
                    <h3 className="text-white/90 text-lg font-medium mb-5">
                      Choose the number of questions to generate
                    </h3>
                    <div className="flex gap-3">
                      {questionCounts.map((count) => (
                        <button
                          key={count}
                          onClick={() => setSelectedCount(count)}
                          className={`
                            flex-1 py-4 px-4 rounded-xl text-base font-medium
                            transition-all duration-200
                            ${selectedCount === count
                              ? 'bg-purple-600 text-white'
                              : 'bg-[#2a2a40]/80 text-white/60 border border-white/10 hover:bg-[#353550] hover:text-white/80'
                            }
                          `}
                        >
                          {count}
                        </button>
                      ))}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>

      {/* Bottom Input Bar - Fixed */}
      <div className="fixed bottom-0 left-0 right-0 bg-gradient-to-t from-[#0a0a1a] via-[#0a0a1a]/95 to-transparent pt-8 pb-6 px-8">
        <div className="max-w-4xl mx-auto">
          {/* Input Container */}
          <form onSubmit={handlePromptSubmit} className="relative">
            <div className="relative flex items-center gap-3 p-2 bg-[#12121f]/90 border border-white/10 rounded-full backdrop-blur-xl">
              {/* PDF Upload Area */}
              <div
                onDragOver={handleDragOver}
                onDragLeave={handleDragLeave}
                onDrop={handleDrop}
                className={`transition-transform duration-200 ${isDragging ? 'scale-105' : ''}`}
              >
                <input
                  ref={fileInputRef}
                  type="file"
                  accept=".pdf,application/pdf"
                  onChange={handleFileInputChange}
                  className="hidden"
                  id="pdf-upload"
                />
                
                {uploadedFile ? (
                  <div className="flex items-center gap-2 py-2.5 px-4 bg-[#1a1a2e]/80 border border-purple-500/30 rounded-full">
                    <FileText className="w-4 h-4 text-purple-400" />
                    <span className="text-white/80 text-sm max-w-[120px] truncate">
                      {uploadedFile.name}
                    </span>
                    <button
                      type="button"
                      onClick={removeFile}
                      className="p-0.5 text-white/40 hover:text-red-400 transition-colors"
                    >
                      <X className="w-3.5 h-3.5" />
                    </button>
                  </div>
                ) : (
                  <label
                    htmlFor="pdf-upload"
                    className={`
                      flex items-center gap-2 py-3.5 px-5 
                      bg-[#1a1a2e]/80 border rounded-full cursor-pointer
                      transition-all duration-200
                      ${isDragging 
                        ? 'border-purple-500 bg-purple-500/10' 
                        : 'border-white/10 hover:border-white/20'
                      }
                    `}
                  >
                    <Upload className={`w-4 h-4 ${isDragging ? 'text-purple-400' : 'text-white/50'}`} />
                    <span className={`text-sm ${isDragging ? 'text-purple-300' : 'text-white/50'}`}>
                      Upload a PDF file
                    </span>
                  </label>
                )}
              </div>

              {/* Text Input */}
              <input
                type="text"
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                placeholder="Add custom instructions (optional)..."
                className="flex-1 bg-transparent text-white/90 placeholder:text-white/30 
                           outline-none text-sm px-2"
              />

              {/* Generate Button */}
              <button
                type="submit"
                disabled={isGenerating || !uploadedFile}
                className={`
                  p-3.5 rounded-full transition-all duration-300
                  ${isGenerating || !uploadedFile
                    ? 'bg-white/10 text-white/30 cursor-not-allowed'
                    : 'bg-purple-600 text-white hover:bg-purple-500 hover:scale-105'
                  }
                `}
              >
                {isGenerating ? (
                  <Loader2 className="w-5 h-5 animate-spin" />
                ) : (
                  <ArrowUp className="w-5 h-5" />
                )}
              </button>
            </div>
          </form>

          {/* Helper text */}
          <p className="mt-3 text-center text-white/30 text-xs">
            Upload a PDF and let AI generate quiz questions for you
          </p>
        </div>
      </div>

      {/* Background effects */}
      <div className="fixed inset-0 pointer-events-none -z-10">
        <div className="absolute top-1/4 left-0 w-[500px] h-[500px] rounded-full bg-purple-600/5 blur-[120px]" />
        <div className="absolute bottom-1/4 right-0 w-[400px] h-[400px] rounded-full bg-blue-500/5 blur-[100px]" />
      </div>
    </div>
  )
}

export default AIGeneratePage